### ISSUE TITLE
Equivalent of -alpha remove?

### ISSUE THREAD

**Issue by hadley** [jeroenooms/magick#11]
I'm using `-background white -alpha remove` to replace transparent pixels with white. I can't see how to replicate that with magick.

**Comment by jsta** [comment]
@hadley  `image_flatten` does this.

**Comment by jeroenooms** [comment]
The following should work. Note that there is a bug in the cran release that results in an error if you use named colors. This is fixed in the dev version. 

```r
image_read("https://jeroenooms.github.io/images/frink.png") %>%
  image_background("pink") %>%
  image_flatten()
```

**Comment by hadley** [comment]
Thanks! Hopefully this is on your long term to do list, but simply pointing to the (not very good) imagemagick docs is not super helpful :(

**Comment by jeroenooms** [comment]
This package is still very alpha. I'm just starting to learn these things myself.
