### ISSUE TITLE
more informative error on unsupported input format?

### ISSUE THREAD

**Issue by sckott** [jeroenooms/magick#4]
perhaps instead of `stopifnot(inherits(x, "magick-image"))` which gives `Error: inherits(image, "magick-image") is not TRUE` which I imagine some new to R may not understand

```r
if (!inherits(x, "magick-image")) {
  stop('expecting object of class magick-image, class ', class(x), ' not supported')
}
```

**Comment by jeroenooms** [comment]
Thanks, it gives a more helpful error message now.
